// Decrypts jasypt ENC(...) values, compatible with the settings cbmy and g5portal use
// (PBEWITHHMACSHA512ANDAES_256, 1000 iterations, RandomSaltGenerator,
// RandomIvGenerator, base64 output), so the same ENC(...) value and master key work here.
//
// jasypt's output is base64(salt[16] || iv[16] || AES-256-CBC ciphertext), with the
// key derived as PBKDF2-HMAC-SHA512(masterKey, salt, 1000 iterations, 32 bytes).

use aes::cipher::{block_padding::Pkcs7, BlockDecryptMut, KeyIvInit};
use anyhow::{anyhow, bail, Context};
use base64::{engine::general_purpose::STANDARD, Engine};
use sha2::Sha512;

type Aes256CbcDec = cbc::Decryptor<aes::Aes256>;

const SALT_LEN: usize = 16;
const IV_LEN: usize = 16;
const ITERATIONS: u32 = 1000;

// Same variable name cbmy reads, so one environment setup covers both.
pub const MASTER_KEY_ENV: &str = "JASYPT_ENCRYPTOR_PASSWORD";

/// Returns `value` unchanged unless it is wrapped in ENC(...), in which case it is
/// decrypted with the master key from JASYPT_ENCRYPTOR_PASSWORD.
pub fn decrypt_if_needed(value: &str) -> Result<String, anyhow::Error> {
    let payload = match value.strip_prefix("ENC(").and_then(|v| v.strip_suffix(')')) {
        Some(payload) => payload,
        None => return Ok(value.to_string()),
    };
    let master_key = std::env::var(MASTER_KEY_ENV).map_err(|_| {
        anyhow!("password is ENC(...) but {} is not set to decrypt it", MASTER_KEY_ENV)
    })?;
    decrypt(payload, &master_key).with_context(|| {
        format!(
            "could not decrypt password - check {} is the right master key for this ENC(...) value",
            MASTER_KEY_ENV
        )
    })
}

pub fn decrypt(payload: &str, master_key: &str) -> Result<String, anyhow::Error> {
    let data = STANDARD
        .decode(payload.trim())
        .context("ENC(...) value is not valid base64")?;
    if data.len() < SALT_LEN + IV_LEN + 16 {
        bail!("ENC(...) value is too short to be a jasypt AES value");
    }
    let (salt, rest) = data.split_at(SALT_LEN);
    let (iv, ciphertext) = rest.split_at(IV_LEN);

    let mut key = [0u8; 32];
    pbkdf2::pbkdf2_hmac::<Sha512>(master_key.as_bytes(), salt, ITERATIONS, &mut key);

    let plain = Aes256CbcDec::new(&key.into(), iv.into())
        .decrypt_padded_vec_mut::<Pkcs7>(ciphertext)
        .map_err(|_| anyhow!("decryption failed (wrong master key or corrupted value)"))?;
    String::from_utf8(plain).context("decrypted password is not valid UTF-8")
}

#[cfg(test)]
mod tests {
    use super::*;

    // Generated by cbmy's scripts/jasypt-enc.jar:
    //   java -jar jasypt-enc.jar testMasterKey 'P@ss wörd;123'
    const SAMPLE: &str = "9sYZNHYHu2bjXYGEeGdICNPRjlQFy0pRufeOb97pFxtTNakNEYJGRnI4oC6OopwH";

    #[test]
    fn decrypts_value_from_jasypt() {
        assert_eq!(decrypt(SAMPLE, "testMasterKey").unwrap(), "P@ss wörd;123");
    }

    #[test]
    fn wrong_master_key_fails() {
        assert!(decrypt(SAMPLE, "wrongKey").is_err());
    }

    #[test]
    fn plain_password_passes_through() {
        assert_eq!(decrypt_if_needed("plainpass").unwrap(), "plainpass");
    }
}
